"""Describe what changed

Revision ID: 812be22dd13e
Revises: 296dd6949985
Create Date: 2025-04-25 19:23:22.018435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '812be22dd13e'
down_revision: Union[str, None] = '296dd6949985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_tasks', sa.Column('base_session_id', sa.Integer(), nullable=True))
    op.alter_column('instruction_sets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_instruction_sets_id'), 'instruction_sets', ['id'], unique=False)
    op.add_column('user_sessions', sa.Column('parent_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_sessions', 'user_sessions', ['parent_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_column('user_sessions', 'parent_session_id')
    op.drop_index(op.f('ix_instruction_sets_id'), table_name='instruction_sets')
    op.alter_column('instruction_sets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('farm_tasks', 'target_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('farm_tasks', 'base_session_id')
    # ### end Alembic commands ###
